# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e67ba465d51221ef64cdc30525292c5f089a9f663d1f317e2c529791987af3d65ecf07a2e2ae1dea1511a256e7e6cf15c1eab0332b1b9c36f7f32eaa6cf5f1a5

test:
  secret_key_base: 9719707c822352eb474e5c6f8bd3fc9564105d9e726de2dc1e425a3b6ef655051fc3f8f870d9f764983da3e34c59495f8855e8ec8d588e1956a0d357c5de0a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
